import 'dart:convert';

import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform;
import 'package:flutter/services.dart' show rootBundle;

/// What a single achievement is, and what it is waiting for.
///
/// The unlock condition is a `trigger` naming a number the game already
/// knows, plus the `target` that number has to reach. Deliberately data
/// rather than code: a new milestone on the campaign ladder — and the
/// campaign is expected to grow well past a thousand levels — should be a
/// line of JSON, not a new branch in a switch.
class Achievement {
  const Achievement({
    required this.key,
    required this.name,
    required this.description,
    required this.points,
    required this.incremental,
    required this.androidId,
    required this.iosId,
    required this.trigger,
    required this.target,
  });

  /// Our own stable name for it. Never leaves the app.
  final String key;

  final String name;
  final String description;

  /// Its share of the game's point budget, 5 to 50.
  ///
  /// Graded by how much play it costs rather than flat, and the range is the
  /// point: Play Games caps the *total* across a game and that cap does not
  /// grow when the campaign does. Spending 50 on something a player earns in
  /// their first minute is borrowing from every milestone a longer campaign
  /// will want later.
  ///
  /// This is a mirror of what was typed into the Play Console, not the source
  /// of truth — the platform awards its own number. It lives here so the
  /// budget can be checked without opening a browser.
  final int points;

  /// Whether the platform shows this as a progress bar.
  ///
  /// **It decides which call unlocks it, so it has to match the Console.**
  /// An incremental achievement cannot be unlocked with `unlock` — the
  /// platform ignores it — and a standard one cannot take steps. Get this
  /// wrong in either direction and the achievement silently never fires.
  ///
  /// True for anything you count toward (levels cleared, cards collected),
  /// because "47 of 100" on the achievements screen is worth having. False
  /// for one-off events like winning in sudden death, where a bar with two
  /// states is just a tick with extra furniture.
  final bool incremental;

  /// The Play Games id, from the Console's games-ids.xml. Empty until the
  /// achievement has actually been created there.
  final String androidId;

  /// The Game Center id, from App Store Connect.
  final String iosId;

  /// Which of [AchievementProgress]'s counters decides this one.
  final String trigger;

  /// What that counter has to reach.
  final int target;

  /// Whether this can be unlocked on *this* platform yet.
  ///
  /// Per-platform rather than "has any id at all", because the two stores are
  /// filled in at different times. The Game Center ids are already written —
  /// App Store Connect lets you choose them, so they are just the keys — but
  /// the Play Games ids are generated by the Console and are still blank.
  /// Treating "has an iOS id" as configured would have Android calling the
  /// plugin with an empty string on every unlock.
  ///
  /// An achievement not configured here is skipped in silence. That is what
  /// lets the whole set ship before the Console work is done: the game
  /// behaves identically, it just has nothing to report to.
  bool get isConfigured => defaultTargetPlatform == TargetPlatform.iOS
      ? iosId.isNotEmpty
      : androidId.isNotEmpty;

  factory Achievement.fromJson(Map<String, dynamic> json) => Achievement(
    key: json['key'] as String,
    name: json['name'] as String? ?? '',
    description: json['description'] as String? ?? '',
    points: (json['points'] as num?)?.toInt() ?? 5,
    incremental: json['incremental'] as bool? ?? false,
    androidId: json['androidId'] as String? ?? '',
    iosId: json['iosId'] as String? ?? '',
    trigger: json['trigger'] as String? ?? '',
    target: (json['target'] as num?)?.toInt() ?? 1,
  );
}

/// The whole set, and the point budget it spends.
class AchievementSet {
  const AchievementSet({required this.all});

  final List<Achievement> all;

  /// What these cost against the platform's cap.
  ///
  /// Worth being able to ask in one line: Play Games caps the total across a
  /// game and the cap does not grow with the campaign, so "how much is left"
  /// is the question to answer *before* adding a milestone, not after.
  int get totalPoints => all.fold(0, (sum, a) => sum + a.points);

  static const AchievementSet empty = AchievementSet(all: []);

  /// Achievements that actually have a platform id behind them.
  Iterable<Achievement> get configured => all.where((a) => a.isConfigured);

  Achievement? byKey(String key) {
    for (final a in all) {
      if (a.key == key) return a;
    }
    return null;
  }

  static Future<AchievementSet> load() async {
    try {
      final raw = await rootBundle.loadString('assets/data/achievements.json');
      return AchievementSet.fromJson(jsonDecode(raw) as Map<String, dynamic>);
    } catch (_) {
      // Same rule as every other optional layer: a broken file takes the
      // feature away, never the game.
      return AchievementSet.empty;
    }
  }

  factory AchievementSet.fromJson(Map<String, dynamic> json) => AchievementSet(
    all: [
      for (final entry in (json['achievements'] as List? ?? const []))
        Achievement.fromJson(entry as Map<String, dynamic>),
    ],
  );
}

/// Every number an achievement can be measured against, in one place.
///
/// Assembled from the profile and from the last match rather than tracked
/// separately, which is why most of these cost nothing: the game already
/// knows how many levels are cleared and what level each card is at. Only
/// [suddenDeathWins] and [deployedPastMidline] are things the match has to
/// remember on purpose.
class AchievementProgress {
  const AchievementProgress({
    this.levelsCleared = 0,
    this.threeStarLevels = 0,
    this.bestCoveragePercent = 0,
    this.suddenDeathWins = 0,
    this.deployedPastMidline = 0,
    this.chestsOpened = 0,
    this.highestCardLevel = 0,
    this.cardsOwned = 0,
  });

  final int levelsCleared;
  final int threeStarLevels;

  /// The best share of the board held in a *won* match. A losing blowout is
  /// not a whitewash.
  final int bestCoveragePercent;

  final int suddenDeathWins;
  final int deployedPastMidline;
  final int chestsOpened;
  final int highestCardLevel;
  final int cardsOwned;

  /// The value a given trigger name is currently at, or null if the name is
  /// not one this knows.
  ///
  /// Returning null rather than zero matters: a typo in the JSON would
  /// otherwise read as "this counter is at zero" and the achievement would
  /// sit there looking merely unearned instead of broken.
  int? valueFor(String trigger) => switch (trigger) {
    'levelsCleared' => levelsCleared,
    'threeStarLevels' => threeStarLevels,
    'bestCoveragePercent' => bestCoveragePercent,
    'suddenDeathWins' => suddenDeathWins,
    'deployedPastMidline' => deployedPastMidline,
    'chestsOpened' => chestsOpened,
    'highestCardLevel' => highestCardLevel,
    'cardsOwned' => cardsOwned,
    _ => null,
  };

  /// Everything now earned, given these numbers.
  List<Achievement> earnedFrom(AchievementSet set) => [
    for (final a in set.all)
      if ((valueFor(a.trigger) ?? -1) >= a.target) a,
  ];
}
