import 'dart:math' as math;

import 'package:flame_audio/flame_audio.dart';
import 'package:flutter/widgets.dart';

/// Every sound the game can make.
///
/// Files live in `assets/audio/` and are generated by
/// `tool/generate_audio.dart` — there is no recorded audio in the project, so
/// retuning a sound is a code change rather than a binary swap.
enum Sfx {
  deploy('deploy.wav'),
  hit('hit.wav'),
  death('death.wav'),

  /// Picks one of three files at random rather than one file pitched three
  /// ways: the variants are already generated a few semitones apart, and
  /// pitching a sample at playback time costs a player rebuild per splat.
  splat('splat_1.wav'),

  elixirFull('elixir_full.wav'),
  leadChange('lead_change.wav'),
  victory('victory.wav'),
  defeat('defeat.wav'),
  chestOpen('chest_open.wav'),
  uiTap('ui_tap.wav');

  const Sfx(this.file);
  final String file;

  /// Whether this sound belongs to the match rather than to the interface.
  ///
  /// The arena does not stop at the final whistle — units already swinging
  /// carry on, keep dying and keep painting — so without this the result
  /// screen sits over a fight that is still audibly going on. Interface and
  /// outcome sounds are exempt: the whole point of the whistle is that the
  /// victory sting plays.
  bool get isGameplay => switch (this) {
    Sfx.deploy ||
    Sfx.hit ||
    Sfx.death ||
    Sfx.splat ||
    Sfx.elixirFull ||
    Sfx.leadChange => true,
    Sfx.victory || Sfx.defeat || Sfx.chestOpen || Sfx.uiTap => false,
  };
}

/// Which loop is playing under the game.
enum Track {
  menu('music_menu.wav'),
  match('music_match.wav'),

  /// The last twenty seconds, with the percussion layer section 12 asks for.
  matchFinal('music_match_final.wav');

  const Track(this.file);
  final String file;
}

/// All sound in one place.
///
/// Deliberately static and deliberately forgiving. Nothing here is allowed to
/// throw into gameplay: audio is decoration, and a device that will not play
/// a wav file should still be able to finish a match. Until [init] succeeds
/// every call is a no-op, which is also what makes the widget tests quiet —
/// they never initialise it, so no test needs an audio plugin.
class Audio {
  const Audio._();

  static bool _ready = false;

  /// True once [init] has completed and sound can actually play.
  static bool get isReady => _ready;

  static double _musicVolume = 0.6;
  static double _sfxVolume = 0.8;

  static Track? _track;

  /// What is playing, or null. Exposed so a screen can avoid restarting a
  /// loop it is already playing.
  static Track? get currentTrack => _track;

  /// Whether [_track] has actually been handed to the player.
  ///
  /// Not the same as "a track is selected": the music can be chosen while the
  /// app is in the background or while the music slider is at zero, in which
  /// case nothing has been loaded and there is nothing to resume — it has to
  /// be started from scratch instead.
  static bool _bgmLoaded = false;

  /// True while the app is not in the foreground.
  static bool _suspended = false;

  /// Silences match sounds without touching the interface ones.
  ///
  /// **Default on, and cleared only while an arena is on screen.** Switching
  /// it on at the final whistle was not enough: that closes the one path that
  /// ends in a whistle and none of the others, and a match left by the back
  /// button never sets it at all. Muted-unless-in-an-arena has no such gaps,
  /// so a menu is silent however you arrived at it.
  ///
  /// Not the same as [_suspended]: the game can still be on screen, and the
  /// result overlay still needs to be able to make a noise.
  static bool gameplayMuted = true;

  /// Exposed for the lifecycle test; nothing in the game reads it.
  @visibleForTesting
  static bool get isSuspended => _suspended;

  static _AudioLifecycle? _observer;

  static final math.Random _random = math.Random();

  /// Last play time per sound, so a brawl does not fire forty identical
  /// cracks in one frame.
  static final Map<Sfx, int> _lastPlayed = <Sfx, int>{};

  /// Minimum gap between two plays of the same sound. Combat sounds get a
  /// tighter gate than one-offs because they are the ones that pile up.
  static const Map<Sfx, int> _gapMs = <Sfx, int>{
    Sfx.hit: 70,
    Sfx.death: 90,
    Sfx.splat: 110,
    Sfx.deploy: 60,
  };

  static const List<String> _splatVariants = [
    'splat_1.wav',
    'splat_2.wav',
    'splat_3.wav',
  ];

  /// The sounds a fight repeats, which get a pool of reusable players.
  ///
  /// This is not a micro-optimisation. `FlameAudio.play` builds a **new**
  /// AudioPlayer for every single shot, and each one costs several platform
  /// channel round trips. A busy fight fires dozens a second, and the
  /// messages Dart was posting outran the rate the Android main thread could
  /// drain them: the queue reached over 150,000 pending DartMessenger
  /// callbacks, input stopped being serviced, and Android killed the app for
  /// not responding. The ANR trace was parked in
  /// `DartMessenger.handleMessageFromDart`, which is that queue exactly.
  ///
  /// A pool reuses a fixed handful of players instead, so playing a sound
  /// costs one call rather than building and tearing down a player.
  static const List<String> _pooled = [
    'hit.wav',
    'death.wav',
    'deploy.wav',
    ..._splatVariants,
  ];

  /// Four is comfortably more than overlap at the gaps in [_gapMs]: the
  /// clips are short, and a fifth simultaneous copy of the same sound is not
  /// audible as anything but volume.
  static const int _poolSize = 4;

  static final Map<String, AudioPool> _pools = <String, AudioPool>{};

  /// Whether [sound] plays through a reused player rather than a fresh one.
  @visibleForTesting
  static bool isPooled(Sfx sound) => sound == Sfx.splat
      ? _splatVariants.every(_pooled.contains)
      : _pooled.contains(sound.file);

  @visibleForTesting
  static List<String> get pooledFiles => _pooled;

  @visibleForTesting
  static List<String> get splatVariants => _splatVariants;

  /// Loads every clip into the cache so the first hit of a match is not the
  /// one that stutters. Safe to call twice; never throws.
  static Future<void> init() async {
    // Before the cache load, and outside the try: a device that cannot play a
    // wav still minimises, and the observer costs nothing when nothing plays.
    watchLifecycle();
    if (_ready) return;
    try {
      await FlameAudio.audioCache.loadAll([
        for (final sfx in Sfx.values)
          if (sfx != Sfx.splat) sfx.file,
        ..._splatVariants,
      ]);
      for (final file in _pooled) {
        _pools[file] = await FlameAudio.createPool(file, maxPlayers: _poolSize);
      }
      _ready = true;
    } catch (error, stack) {
      // A device with no audio support is not a reason to fail to boot.
      debugPrint('Audio disabled: $error');
      debugPrintStack(stackTrace: stack);
      _ready = false;
    }
  }

  /// Starts listening for the app going to and from the background.
  ///
  /// Without this the music keeps playing over whatever the player switched
  /// to. `flame_audio`'s [Bgm] can do this itself, but only once its own
  /// `initialize()` has registered its observer, and that call also quietly
  /// switches the audio focus policy — so the game owns the behaviour here
  /// instead, where a test can drive it.
  ///
  /// Safe to call twice.
  static void watchLifecycle() {
    if (_observer != null) return;
    final observer = _AudioLifecycle();
    _observer = observer;
    WidgetsBinding.instance.addObserver(observer);
  }

  /// Pauses everything when the app leaves the foreground, and picks the
  /// music back up when it returns.
  ///
  /// Anything other than [AppLifecycleState.resumed] counts as gone: the
  /// player has switched away, pulled the shade down or taken a call, and in
  /// none of those cases should this game still be making noise.
  static void handleLifecycleState(AppLifecycleState state) {
    final foreground = state == AppLifecycleState.resumed;
    if (foreground == !_suspended) return; // Nothing changed.
    _suspended = !foreground;

    if (_suspended) {
      if (_ready && _bgmLoaded) {
        try {
          FlameAudio.bgm.pause();
        } catch (_) {
          // No plugin, or nothing loaded. Silence either way.
        }
      }
      return;
    }

    if (!_ready || _track == null || _musicVolume <= 0) return;
    if (_bgmLoaded) {
      try {
        FlameAudio.bgm.resume();
      } catch (_) {
        _bgmLoaded = false;
      }
    } else {
      // Chosen while we were away, so there is nothing paused to resume.
      _startTrack();
    }
  }

  /// Both sliders, 0..1, straight from the saved profile.
  static void setVolumes({required double music, required double sfx}) {
    final wasSilent = _musicVolume <= 0;
    _musicVolume = music.clamp(0.0, 1.0);
    _sfxVolume = sfx.clamp(0.0, 1.0);
    if (!_ready) return;
    try {
      if (_musicVolume <= 0) {
        _bgmLoaded = false;
        FlameAudio.bgm.stop();
      } else if (wasSilent) {
        // Coming back from muted. Dropping to zero *stops* the player rather
        // than pausing it, so setting a volume on it here would play nothing
        // at all — and the screen will not ask again, because as far as it is
        // concerned this track is already the one on. Start it over.
        if (!_suspended && _track != null) _startTrack();
      } else {
        FlameAudio.bgm.audioPlayer.setVolume(_musicVolume);
      }
    } catch (_) {
      // Nothing playing yet, or no plugin. Either way, not worth reporting.
    }
  }

  static void play(Sfx sound, {double volume = 1.0}) {
    if (!_ready || _sfxVolume <= 0 || _suspended) return;
    if (gameplayMuted && sound.isGameplay) return;

    final gap = _gapMs[sound];
    if (gap != null) {
      final now = DateTime.now().millisecondsSinceEpoch;
      final last = _lastPlayed[sound];
      if (last != null && now - last < gap) return;
      _lastPlayed[sound] = now;
    }

    final file = sound == Sfx.splat
        ? _splatVariants[_random.nextInt(_splatVariants.length)]
        : sound.file;

    final level = (_sfxVolume * volume).clamp(0.0, 1.0);
    try {
      final pool = _pools[file];
      if (pool != null) {
        // Fire and forget: the future completes with a stop function nobody
        // needs, and awaiting it would put a frame's worth of latency on a
        // hit sound.
        pool.start(volume: level).catchError((Object _) => () async {});
      } else {
        FlameAudio.play(file, volume: level);
      }
    } catch (_) {
      // Dropped sounds are not worth a log line per swing.
    }
  }

  /// Starts [track] looping, or does nothing if it is already the one
  /// playing. Music restarts are audible, so this guard matters.
  static Future<void> playMusic(Track track) async {
    if (!_ready || _musicVolume <= 0) {
      _track = null;
      return;
    }
    if (_track == track) return;
    _track = track;

    // Remember the choice but do not make a sound: the player is in another
    // app. Coming back to the foreground starts it.
    if (_suspended) {
      _bgmLoaded = false;
      return;
    }
    await _startTrack();
  }

  /// Hands [_track] to the player. Assumes the caller has already checked
  /// that we are ready, unmuted and in the foreground.
  static Future<void> _startTrack() async {
    final track = _track;
    if (track == null) return;
    try {
      await FlameAudio.bgm.play(track.file, volume: _musicVolume);
      _bgmLoaded = true;
    } catch (_) {
      _track = null;
      _bgmLoaded = false;
    }
  }

  static Future<void> stopMusic() async {
    _track = null;
    _bgmLoaded = false;
    if (!_ready) return;
    try {
      await FlameAudio.bgm.stop();
    } catch (_) {
      // Already stopped.
    }
  }

  /// Test seam: pretends audio is unavailable, so nothing tries to play.
  @visibleForTesting
  static void resetForTest() {
    _ready = false;
    _track = null;
    _bgmLoaded = false;
    _suspended = false;
    gameplayMuted = true;
    _pools.clear();
    _lastPlayed.clear();
    final observer = _observer;
    if (observer != null) {
      WidgetsBinding.instance.removeObserver(observer);
      _observer = null;
    }
  }
}

/// Forwards the binding's lifecycle callbacks into [Audio].
///
/// A separate object rather than making [Audio] itself an observer, because
/// [Audio] is deliberately all-static: there is one game and one mixer, and a
/// screen should not be able to hold the wrong instance of it.
class _AudioLifecycle extends WidgetsBindingObserver {
  @override
  void didChangeAppLifecycleState(AppLifecycleState state) =>
      Audio.handleLifecycleState(state);
}
